title: "Anushka Gupta"
author: "Anushka Gupta"
description: "Indian Institute of Technology Guwahati"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {url: "/", title: "Home", sidebaricon: home}
  - {url: "/assets/anushka.pdf", title: "CV", sidebaricon: home}
  - {file: "publications.md", title: "Publications", sidebaricon: file-alt}
  - {file: "experience.md", title: "Experience", sidebaricon: briefcase}
  - {file: "achievements.md", title: "Achievements", sidebaricon: trophy}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:g.anushka@iitg.ac.in"}
  - {title: Github, icon: github, url: "https://github.com/anushkacodez"}
  - {title: LinkedIn, icon: "linkedin", url: "https://www.linkedin.com/in/anushkagupta2007/"}
  - {title: Instagram, icon: "instagram", url: "https://www.instagram.com/iamanushkag/"}
  - {title: Github, icon: "github", url: "https://github.com/anushkacodez"}
  # - {title: Codeforces, icon: "codeforces", url: "https://codeforces.com/anushkagupta1331"}


comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
